server:
#    port: 8080
    error:
        include-message: always
        include-binding-errors: always

spring:
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: root
        initialization-mode: always
    security:
        oauth2:
            client:
                registration:
                    google:
                      clientId: 106286138287-s2j6k6dfksf5b9megsc54slm97pd544u.apps.googleusercontent.com
                      clientSecret: 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
                      clientAuthtnticationScheme: form
                      authenticationScheme: query
                      scope: profile, email

                      redirectUri: http://localhost:8080/oauth2/authorization/google
                      userAuthorizationUri: http://accounts.google.com/o/oauth2/v2/auth

                      accessTokenUri: http://www.googleapis.com/oauth2/v3/token

                      tokenName: oauth_token

                      userInfoUri: http://www.googleapis.com/userinfo/v2/me

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

